### ISSUE TITLE
.ogg files on IOS not supported

### ISSUE THREAD

**Issue by jpkelly** [mi-ael/genkikani#2]
Error playing audio files on iOS.
.ogg files not supported

**Comment by mi-ael** [comment]
I'm sorry, but I won't be changing anything on this project anymore, because I'm kinda busy with other stuff right now. If you want to fix it yourself and if you can get the code to run (not sure if the download links still work) the format of the sound files is defined in https://github.com/mi-ael/genkikani/blob/master/download_wanikani_data.py line 13.
